site_name: pyhydroqc Documentation
repo_name: AmberSJones/pyhydroqc
repo_url: https://github.com/AmberSJones/pyhydroqc

theme:
  name: material

plugins:
  - mkdocstrings
  - search
  - mknotebooks:
      binder: true
      binder_service_name: 'gh'
      binder_branch: 'master'
      binder_ui: 'lab'

markdown_extensions:
  - tables

nav:
  - Functions: index.md
  - About: about.md
  - Example: SingleSiteExample.ipynb